sunbeam-labs/sunbeam

rules/qc/qc.rules
tests/test.sh

- Cutadapt now only executes if the forward and/or reverse adapters are specified in the config file, otherwise it symlinks the files into the `qc/cutadapt` directory
- Cutadapt now requires overlap equal to the length of the smallest adapters specified before removing a read to reduce incidences of false read removal

Optional cutadapt

---

rules/assembly/assembly.rules

for negative control samples, there might be no contigs assembled. and for empty cap3-contigs.fa case, vsearch (final_filter rule) gave error: Unable to read from file (cap3-contigs.fa).
Fixed: copy cap3-contigs.fa as the output of the rule final_filter

fix vsearch empty fasta error

---

sunbeamlib/initialize.py

add an option for sunbeam_init --custom_configfile_fp: if this argument is provided, then it will be used as the template for generating config file for snakemake. This feature will be very helpful for testing purpose for newly added rules.

Config file

---

tests/test.sh

Add the option for test.sh suggested by @kylebittinger 
-- if a directory is passed to the test.sh script, then the test output should be written there. Otherwise, the output should be written to a temp file and removed, as it is now.
Not sure about the "trap cleanup EXIT". Since the point is to inspect the intermediate files, we would not want cleanup. Yet we might want to keep this for the tmp file though... Any suggestions?

add non temp test dir option

---

.travis.yml
Snakefile
install.sh
install_igv.sh
requirements.txt
rules/mapping/bowtie.rules
rules/targets/targets.rules
sunbeamlib/__init__.py
sunbeamlib/data/default_config.yml
sunbeamlib/igv.py
tests/prep_config_file.py
tests/targets.txt
tests/test.sh

This adds new rules for aligning all samples present to each sequence in each genome file present, using bowtie2/samtools for the alignments and IGV for a graphical representation of each alignment.  The tests are updated to check for the right image files, but no new data files have been added.  The test setup also does a basic install of IGV into `sunbeam/local`, with a configuration option for the path to the IGV executable.
Some things to note:
* I added a new helper function to `sunbeamlib/__init__.py` that reads out sequence identifiers from a given fasta file.  There are IGV-related functions still in bowtie.rules.
* To match the paths used by the existing index_files function, I rewrote my original rules to put the bowtie2 index files inside the indexes directory itself rather …

Add mapping rules using bowtie2 and IGV

---

rules/mapping/bowtie.rules
sunbeamlib/data/default_config.yml
sunbeamlib/igv.py

This fixes #59 by adding support for specifying IGV options via the sunbeam configuration file.  A dictionary of name/value pairs called igv_prefs in the mapping section is used to populate an IGV preferences override file.  The BAM filenames are also sorted when given to igv.render() in the mapping rules so that the alignment image stacks will be organized and ordered in a predictable way.

Add IGV preferences support for mapping rules

---

rules/mapping/bowtie.rules
rules/targets/targets.rules
sunbeamlib/samtools.py
tests/targets.txt

This adds a rule to the mapping section for creating some coverage statistics per genome across samples.
It outputs a table in CSV format for each target that summarizes per genome/segment/sample combination:
* min/max/mean/stddev of depth
* coverage of genome segment in number of bases
* length of genome segment in number of bases

Add coverage statistics for mapping rules

---

rules/mapping/bowtie.rules
sunbeamlib/data/default_config.yml

This adds a `keep_unaligned` boolean to the mapping section of the Sunbeam configuration, which controls whether unaligned reads are stored in bowtie2's alignment output.  By default `keep_aligned` is False, and `--no-unal` is appended to the bowtie2 alignment commands.

Fix #66: default to --no-unal option for bowtie2

---

sunbeamlib/igv.py

This parses the length of each genome sequence and explicitly tells IGV
to always show the full sequence, using a command like "goto
<sequence_id>:1-<sequence_length>".  This should ensure that IGV doesn't
leave the view zoomed in by some arbitrary amount when rendering
alignment images.

Fix #68: Show full length for IGV alignment images

---

requirements.txt

When run under the latest Snakemake available from the bioconda Anaconda channel, multiple rules fail because some of the Snakemake objects have changed. Version 3.13.2 fails, but 3.13.0 still works.  This sets our requirement for Snakemake to version 3.13.0 explicitly.

Fix #74: specify snakemake=3.13.0 in requirements

---

.travis.yml
rules/assembly/assembly.rules
sunbeamlib/igv.py
tests/generate_dummy_data.py
tests/targets.txt

This adds a check for an empty input file for the "cap3" rule.  In that case the file is just passed along to the output, bypassing cap3.  The subsequent rules "save_intermediates" and "final_filter" are able to handle empty files already, so the assembly step should now run to completion even for samples where no contigs can be built.
For testing, this adds a third dummy fastq input pair, using arbitrary reads so that no contigs are build by IDBA-UD.  cap3 would then fail with a segmentation fault as described in #39, but bypassing it with the shell avoids that problem.

Fix #39: Bypass cap3 for empty contigs in assembly rules

---

Readme.md
rules/mapping/bowtie.rules

This changes the rule `bowtie2_all` to `all_mapping` to match the existing pattern, and adds a description of the mapping rules and functionality to the Readme file.

Fix #72: Document mapping rules, IGV image feature

---

rules/qc/qc.rules

custom_removal should not be a local rule

---

.travis.yml
Snakefile
conda-requirements.txt
setup.py
sunbeamlib/__init__.py
sunbeamlib/config.py
sunbeamlib/data/default_config.yml
sunbeamlib/initialize.py
tests/test.sh

This update now versions `sunbeamlib` according to the git tags on each release, and `sunbeam_init` writes that into config files. When calling `snakemake`, a check is performed to ensure the major versions of the config file and `sunbeamlib` are the same. To get around this check, a user can manually edit the version number in the config file (for debugging).

Semantic versioning

---

.travis.yml
conda-requirements.txt
install.sh
tests/test.sh

This now tests the install process as well as the workflow by installing sunbeam into a new conda env (named `sunbeam-$TMPDIR` based on the temporary testing directory) that gets removed after successful testing.
- Fixes #77

Test.sh tests installation; update to Snakemake dep. version

---

conda-requirements.txt
docs/usage.rst
rules/qc/decontaminate.rules
rules/qc/qc.rules
sunbeamlib/data/default_config.yml
tests/test.sh

This incorporates [komplexity](https://github.com/eclarke/komplexity) to mask low-complexity sequences before host read removal. I've chosen to use masking rather than read removal for simplicity and because that's what we've been testing for the manuscript. 
- `mask_low_complexity`: can be either true or false. If false, masking is skipped.
- `kz_threshold`: threshold between 0-1 for komplexity (kz)
- `kz_window`: window size for komplexity, in bp
With many thanks to @louiejtaylor for packaging komplexity for conda.

integrate low-complexity masking using komplexity

---

environment.yml
rules/qc/decontaminate.rules

Removes dependency on bbtools in favor of rust-bio-tools for fastq filtering.

use rbt for fastq filtering

---

rules/assembly/assembly.rules

negate default 50k max seq length for contigs

---

rules/qc/decontaminate.rules
rules/reports/reports.rules

decontam counts for each host 

---

Snakefile
sunbeamlib/__init__.py
sunbeamlib/scripts/init.py
sunbeamlib/scripts/list_samples.py
sunbeamlib/scripts/run.py

This should fix #139, an edge case that may occur with only one pair of read files, and potentially another underlying issue converting PosixPath to str implicitly (maybe only on Python 3.5?)

Bugfixes for `sunbeam run`

---

sunbeamlib/__init__.py
sunbeamlib/scripts/list_samples.py
tests/test_suite.bash

Bugfixes related to sample name guessing. In particular:
- can now work with sample names that have consistent ends (like `_001.fastq.gz`) but inconsistent numbers of underscores preceding the end (like `extractionblank_S01_L001_R1_001.fastq.gz` vs `S_123_S01_L001_R1_001.fastq.gz`)
- now understands and ignores index files (I1 and I2) in the data directory
- added new tests for sample parsing edge cases like these
Fixes #146.

Sample name guessing

---

environment.yml

Trimmomatic dependency lock

---

docs/quickstart.rst

so that users can copy-paste without syntax error

change backtick to single quote

---

sunbeamlib/scripts/init.py

More robust project folder creation [DO NOT MERGE YET]

---

Snakefile
sunbeamlib/config.py
tests/test_suite.bash

Fix 153: paths in config must be subdirectories to be used

---

rules/mapping/mapping.rules
sunbeamlib/samtools.py
tests/test_suite.bash

This updates samtools.get_coverage_stats to stream samtools' output text instead of holding it in memory, and reorganizes the Snakemake mapping rules to run separately for each sample until a final concatenation step.

Fix 154: reorganize CSV generation in mapping rules

---

Snakefile
environment.yml
rules/assembly/assembly.rules
rules/assembly/coverage.rules
rules/targets/targets.rules
tests/targets.txt

* [V] I have run `bash tests/test.sh` on a local deployment and the tests passed successfully
* [V] If this adds a new output file, I have added a check to tests/targets.txt
* [V] If this adds or modifies a rule that uses FASTQ files, the input accepts gzipped FASTQ and outputs gzipped FASTQ, or marks uncompressed FASTQ output as `temp`
After de novo the contigs, we added the mapping reads back to all the contigs using minimap2 to get the per-base coverage statistics. This is helpful for any extensions based need to quantify the genes' abundance (e.g. RPKM).

Contigs coverage

---

rules/assembly/assembly.rules
rules/classify/kraken.rules
rules/qc/decontaminate.rules
rules/qc/qc.rules

I added dummy output for `qc`, `decontaminate`, `assembly` and `classify` rules, which can be easily used in the extensions. For example, for any extensions that needs the fastq files from the decontam, we can simply use `rules.Decontaminated.output` as the input. For any extensions that built on the `contigs`,  we can simply use `rules.Assembled.output`.

Dummy output

---

sunbeamlib/scripts/get.py
tests/test_suite.bash

For `test_sunbeam_get` I switched from SRP159164 to SRP021545 to ensure we have an unpaired-only test case.  (Fixes #177.)
For `test_get_paired_unpaired` I finished our test of the  mixed paired/unpaired case and included checks on the config files as well as the sample lists.    (Fixes #176.)

Fix sunbeam get tests and paired/unpaired feature

---

rules/annotation/blast.rules

1. The issue with `--max_target_seqs 1` is that: max target sequences are applied in an early ungapped phase of the algorithm, as well as later, aka the **internal alignment limit** mentioned in this [blog](https://blastedbio.blogspot.com/2018/11/blast-max-alignment-limits-part-four.html). In some cases a final HSP will improve enough in the later gapped phase to rise to the top hits. Therefore a small `max_target_seqs` may end up with a incomplete search and report the top hits related to the database order. 
On the other hand, `blast[px]` and `blastn` are using different equation for this internal search limit, and considering the number of refseq genomes of well studied bacteria strains, I think 5000 should be a good candidate.
2. Due to the large space XML files take, we added a …

rule blast xml to txt and another rule to clean blast

---

rules/mapping/mapping.rules
tests/test_suite.bash

This previously used cleaned (i.e. post-qc but pre-decontam) reads as input to the mapping rules. This pull request suggests using the post-decontam reads instead. I'm not sure if this is by-design, so please reject this PR if so.

Change input to mapping rules to decontam'd reads

---

docs/_static/theme_overrides.css
docs/conf.py
docs/extensions.rst
docs/usage.rst

I didn't add any new Python code, except for a small change to the config file for the documentation.  All changes are in the `docs/` subdirectory.  I re-built the documentation and checked the output.
I added a thorough tutorial for making Sunbeam extensions.  It includes a table of all the standard hooks for Sunbeam output files, and a table of Python variables that might be used in a rules file.  The tutorial gives two examples: the MetaSPAdes assembler, and an R Markdown report.

Extension docs

---

Snakefile
tests/run_tests.bash
tests/sbx_test_subdir/sbx_test_subdir.rules
tests/test_suite.bash

This creates a top-level `wildcard_constraints` entry in the Snakefile to disallow slashes in sample names when Snakemake builds its dependency graph and tests out different possible wildcard values.  This fixes #185.
This is a small change, but it's a modification to Snakemake's settings for the whole tree, so I want to make sure all looks good and I'm not missing anything.  I added an extension-based test to the test suite (modeled after sbx_test) that demonstrates the problem.  I also skimmed the rules files for existing extensions to make sure nothing is somehow relying on the existing behavior, and nothing jumped out at me, but I'll be glad to have any others' input too.

Enforce sample wildcard constraints

---

rules/assembly/assembly.rules

Use the same `Cfg[section]['threads']` idiom used elsewhere to control megahit's multithreading via the config file.  We already have an entry for it in the default config file, but it wasn't in use.  This fixes #188.
This doesn't add any more detailed output checking than we already have, but that could be a separate improvement on the testing side.

Run megahit multithreaded

---

rules/assembly/assembly.rules
tests/test_suite.bash

This fixes #167 (in my view) by making megahit failures more obvious for every exit code except the 255 "Empty contigs" case.  Here if the exit code is anything except 255 (which will include 137 for SIGKILL/out-of-memory cases) no output file appears and the rule fails.  The output messages @zhaoc1 previously set up for these cases still appear as before.  Chunyu how does this sound to you?
One thing: For the new test case I used mock megahit executables (just tiny bash scripts) to produce the different exit codes.  It's not quite a real test of megahit, but since it does test the rule behavior, I figured that was enough.

New megahit failure handling

---

environment.yml
tests/test_suite.bash

This switches conda-forge to have a higher priority than bioconda in our environment definition file, matching #181 and [the bioconda instructions](https://bioconda.github.io/#set-up-channels).  @louiejtaylor had previously identified a channel issue that could be resolved in the user's config but it needs to be applied at install-time (fixes #200).  An otherwise unrelated test is updated here as well (test_mapping) so that all tests now pass with the latest available package set.

Update conda channel priority during install

---

rules/qc/qc.rules

Hi,
First of all, thank you for your work, I have just started using sunbeam and it is great and straightforward to use.
I did not find any information on the way to contribute so here is a small PR to take the `threads` parameter set up for `qc` step also by `cutadapt`.
Best regards,
Kenzo
_edit thanks to @ressy comment_:
Closes #197

Consider threads for cutadapt in qc

---

environment.yml
rules/qc/qc.rules
rules/reports/reports.rules
rules/targets/targets.rules
sunbeamlib/scripts/init.py
tests/targets.txt

As promised, here is another PR, more as a POC for the use of [MultiQC](https://multiqc.info/) in the `qc` step.
In the future, if the rule is also used in other steps to get a summary of them, I guess we could put it in an independant `.rules` file and include this generalized rules in every concerned step.
Since a new rule is here added and I was not sure on the way to proceed, I apologize in advance if I put things in the incorrect place or named variable without respecting your own development rules.
Cheers,
Kenzo

Add multiQC to build QC report

---

.circleci/config.yml

This is just a change to the CircleCI configuration to extend the timeout waiting for output during the install step, but I'd like to merge this into stable directly so we don't get false positives during testing.  Fixes #210.

Specify longer CircleCI output timeout during install

---

environment.yml
tests/test_suite.bash

This updates the conda environment file to require megahit below version 1.2.  I also added en explicit error message for a related test failure in test_all.  This fixes #213.  I'd like to merge this straight into stable so new installs work as expected again; we can then update and finish off #204 and sync it all back with dev too.

Require megahit <1.2

---

Readme.md

I'm proposing naming the recent package-version hotfixes as 2.0.1.  Those commits went in separately so this just updates the changelog to match and gives a verified commit to tie to the tag + release.
Specifically it covers:
* megahit < 1.2 (#216)
* snakemake=5.5.0 (#204/#215)
* Minor CircleCI configuration change (#211)

Sunbeam version 2.0.1

---

environment.yml

This is a quick fix for #214, which failed at kraken result processing post-classification. See #214 for an in-depth discussion of the issue and long-term plans.

add h5py to environment.yml

---

install.sh
tests/run_tests.bash

This PR is related to issue #198 (and was also brought up in #204 by @scottdaniel). Now the install and test scripts use "conda [de]activate" rather than "source [de]activate". No more warnings!

Use "conda activate" instead of "source activate"

---

.circleci/config.yml

This is a change to the test configuration only, to schedule an automatic weekly build in CircleCI for dev and stable.  I figure this should help us catch dependency/version-related problems even if we haven't changed anything lately.

Schedule weekly build in CircleCI

---

rules/qc/qc.rules
sunbeamlib/qc.py
tests/generate_dummy_data.py
tests/run_tests.bash
tests/test_suite.bash

This changes the graph at the very start of the QC rules to optionally strip off a configurable suffix for sequence IDs, to ensure that pairs always use the same ID, as generally expected.  Fixes #221.  (If this feature isn't enabled it will just symlink the original files into place instead.)  This allows us to work with older-style Illumina sequence IDs that end with /1 and /2 for R1 and R2, or any other suffix pattern that might be used.

Add support for sequence IDs with read suffix (Old Illumina)

---

docs/usage.rst
rules/qc/qc.rules
sunbeamlib/data/default_config.yml
tests/test_suite.bash

This finalizes the new sequence ID normalizing feature (See #238) by adding it to the default configuration file, and expands on one point in the usage documentation.  Fixes #244.

Add seq_id_ending to default configuration

---

Readme.md
docs/extensions.rst
docs/usage.rst
environment.yml
sunbeamlib/scripts/command.py
sunbeamlib/scripts/extend.py
tests/test_suite.bash

This PR introduces a new subcommand: `sunbeam extend`, which installs Sunbeam extensions from a GitHub repository URL. The `sunbeam extend` logic is encapsulated in the new file `sunbeamlib/scripts/extend.py `. Other inclusions: new test, README update, documentation updates describing this new feature. This PR closes #251.

Simplify install process for sunbeam extensions

---

environment.yml

Quick PR to remove the pinned jellyfish dependency before trying to figure out what's gone wrong with the merge of `sunbeam extend`

remove jellyfish from env

---

Readme.md
docs/extensions.rst
docs/usage.rst
environment.yml
sunbeamlib/config.py
sunbeamlib/scripts/command.py
sunbeamlib/scripts/extend.py
tests/test_suite.bash

This PR (re)introduces a new subcommand: `sunbeam extend`, which installs Sunbeam extensions from a GitHub repository URL. The `sunbeam extend` logic is encapsulated in the new file `sunbeamlib/scripts/extend.py `. Other inclusions: new test, README update, documentation updates describing this new feature. Related to #251.

Easier installation for extensions

---

sunbeamlib/scripts/extend.py
tests/test_suite.bash

Quick bugfix for `sunbeam extend`. This bug is described in, and this commit fixes #261.

Handle trailing slash in url passed to `sunbeam extend`

---

environment.yml

Make blis dependency explicit (for now); fixes https://github.com/sunbeam-labs/sunbeam/issues/286

Add explicit blis depencency

---

.circleci/config.yml
Readme.md
environment.yml
install.sh
tests/test_suite.bash

This addresses a few different things to get our tests passing again:
* Allow the use of [mamba](https://github.com/mamba-org/mamba) as an alternate dependency solver and use it for CircleCI testing.  This is so that the automated tests can install the environment in a reasonable amount of time (and real installs too, with `./install.sh -m`) and with lower RAM usage.  If mamba is already installed it will be used to set up the environment.
* Require megahit >1.1.2 as we all <1.2.  Recently the dependency resolution has been installing the earliest available megahit package on bioconda, which incidentally has all of its executables stored at the top level of the environment instead of in `$CONDA_PREFIX/bin`.  This ensures that version won't get installed and in the long run we'll probably …

Various testing and dependency fixes

---

install.sh

This attempts to address a confusing situation (at least for me) when trying to install Sunbeam from a git archive instead of a clone of the repo

added sanity check to warn against installing from a .tar.gz git archive, which raises a setuptools_scm error

---

docs/usage.rst

Fixes #281 by forcing documentation to display `"` (U+0022 : QUOTATION MARK) instead of `“` (U+201C : LEFT DOUBLE QUOTATION MARK).

add backticks to doc quotations

---

.circleci/config.yml
environment.yml

For some reason, rust-bio-tools, now that we got it updated to include blis as a dependency (#289), now depends on mkl as well (or instead? I actually *don't* see libblis used by the rbt binary in the latest builds).  I described my confusion about that in bioconda/bioconda-recipes#27826 but for our purposes adding mkl to our environment file seems to get it working again. Fixes #293.

Add explicit mkl dependency for rust-bio-tools

---

install.sh
sunbeamlib/scripts/run.py
tests/test_suite.bash

Always move --configfile to end of arg list

---

rules/annotation/annotation.smk
rules/annotation/blast.smk
rules/annotation/orf.smk
rules/assembly/assembly.smk
rules/assembly/coverage.smk
rules/classify/kraken.smk
rules/download/download.smk
rules/mapping/mapping.smk
rules/qc/decontaminate.smk
rules/qc/qc.smk
rules/reports/reports.smk
rules/targets/targets.smk

Remove `str` statements from around Path objects (new as of Python 3.9)

Remove strs

---

sunbeamlib/config.py
sunbeamlib/scripts/_config.py

Fix sunbeam config modify not working for extensions

---

.github/workflows/test_tar_release.yml
.gitignore
docs/commands.rst
environment.yml
src/sunbeamlib/post.py
src/sunbeamlib/script_run.py
src/sunbeamlib/slurm_profile.yaml
workflow/Snakefile

Add input file sizes to benchmarking data collected
Deprecate --target_list option of sunbeam run
Fix config for filter_reads rule
If this is for a release:

Improve benchmarking reports

---

src/sunbeamlib/qc.py

Update qc.py for filter komplexity id bug

---

.github/workflows/integration-tests.yml
environment.yml
install.sh
src/sunbeamlib/slurm_profile.yaml
workflow/Snakefile
workflow/rules/qc.smk

Use hack to create slurm_extra resource within each rule

---

.github/workflows/integration-tests.yml
docs/commands.rst
docs/examples.rst
pyproject.toml
src/sunbeamlib/__init__.py
src/sunbeamlib/script_run.py
workflow/Snakefile
workflow/rules/qc.smk

Remove hack

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/release.yml
Dockerfile
docs/examples.rst
install.sh
slim.Dockerfile
workflow/envs/cutadapt.Dockerfile
workflow/envs/komplexity.Dockerfile
workflow/envs/qc.Dockerfile
workflow/envs/reports.Dockerfile

Include docker image reports (mostly package versions) in releases

---

.github/workflows/release.yml
install.sh
src/sunbeamlib/parse.py
src/sunbeamlib/qc.py
workflow/scripts/filter_reads.py
workflow/scripts/remove_low_complexity.py

485 fix filter reads and remove low complexity memory inefficiency

---

src/sunbeamlib/__init__.py

Add universal extension path function to sunbeamlib
