sunbeam-labs/sunbeam

configs/cluster.json
configs/example_config.yml
configs/respublica_config.yml

- also add cluster.json for resources requirement when using cluster

fix r2 typo in qc.rules

---

configs/example_config.yml
rules/qc/qc.rules

Hi Chunyu, please make sure your .gitignore includes files like .DS_store. We don't want to commit these to the repository.

Revert "r2 typo in qc"

---

requirements.txt
rules/classify/kraken.rules
rules/targets/targets.rules

The Krona output files were okay for testing the classifiers, but a more useful final product is a biom file similar to the end output of QIIME, which includes a counts matrix and taxonomy. I've updated the classify/kraken.rules and targets.rules to reflect this.
@zhaoc1 what do you think?

classify end point is now biom table

---

rules/targets/targets.rules

the TARGET_* variables need to be list, instead of str. Minor fix. I am going to merge it. Thank you:)

TARGET_KRAKEN list not str

---

rules/assembly/assembly.rules
rules/assembly/pairing.rules
rules/classify/classify.rules
rules/targets/targets.rules
tests/test.sh

mainly change the assembly.rules to add clean up intermediates files. update corresponding part in the targets.rules.
also update the pairing rules for further use.
Update the krona_taxonomy in classify.rules, by adding the dir of "updateTaxonomy.sh"
Finally, update the test.sh file to only build kraken/blast db once. @eclarke could you please double check the bash script for this section? Thank you!!

add cleanup

---

sunbeam/config.py

remove home dir

---

tests/test.sh

revise the test.sh and now travis should work.

update test.sh for travis

---

rules/qc/decontaminate.rules
sunbeamlib/data/default_config.yml

fix for #40

---

.gitignore
Snakefile
rules/assembly/assembly.rules
sunbeamlib/__init__.py
tests/test.sh

For the data_fp in the config file, provide either a dir of all the files, or a tab delimited barcode files.
Also minor change about the workdir.

add build samples from barcodes

---

Snakefile
rules/qc/decontaminate.rules

Add thread parameter to decontaminate rules

Decontam threads

---

sunbeamlib/initialize.py
tests/test.sh

1. remove the main() from sunbeamlib.initialize.py
2. fix the bug by format the CONDA_FP and PROJECT_FP with custom config file
3. add a test for custom config in the test.sh

Test template

---

sunbeamlib/igv.py

This uses the "-a" argument to xvfb-run to allow it to automatically select the first available X server, so that multiple calls to `igv.render()` in parallel won't conflict with each other.

Fix #70: Make IGV image rule work in parallel

---

.github/PULL_REQUEST_TEMPLATE.md

This adds a series of checks before PRs that codify some of the conventions we already followed

add pull request checklist template

---

install.sh
setup.py

make sunbeamlib an editable install

---

rules/assembly/assembly.rules

pull fix from dev

---

environment.yml

bwa dependency minimum

---

docs/usage.rst
sunbeamlib/scripts/command.py
sunbeamlib/scripts/get.py

Sunbeam get fixes (close #171)

---

docs/index.rst

This should also help clarify issue #195 .

Update documentation to spell out requirements

---

.circleci/config.yml
environment.yml
tests/test_suite.bash

Re-doing #204 to try to re-trigger the automated tests.

update snakemake for newer versions of conda

---

Readme.md
environment.yml
rules/classify/kraken.rules
tests/run_tests.bash

This PR upgrades kraken to kraken2. This will close #253.

Replace kraken with kraken2

---

Readme.md

Quick readme updates with usage examples (this probably didn't need a branch, but I'm in the habit...).

Readme updates with usage examples

---

.circleci/config.yml
.circleci/dump_conda_env.bash
docs/quickstart.rst
docs/usage.rst
environment.yml
install.sh
manage-version.sh

Add manage-version.sh

---

docs/install.rst
docs/manage-version.rst
docs/usage.rst

Update docs for v3.1.0 release

---

docs/commands.rst
docs/manage-version.rst
manage-version.sh
sunbeamlib/scripts/run.py

Allow multiple targets

---

envs/annotation.yml
envs/classify.yml
envs/qc.yml
envs/reports.yml
sunbeamlib/data/slurm_profile.yaml

Profiles update patch

---

Readme.md
docs/extensions.rst

Update extension submission

---

.tests/unit/sunbeamlib/test__init__.py
install.sh
sunbeamlib/__init__.py
sunbeamlib/data/default_config.yml
sunbeamlib/data/slurm_profile.yaml
sunbeamlib/parse.py
sunbeamlib/qc.py
workflow/rules/qc.smk
workflow/scripts/remove_low_complexity.py
workflow/scripts/sample_intake.py

Cleanup sunbeamlib

---

docs/quickstart.rst
docs/structure.rst
docs/usage.rst
sunbeamlib/reports.py
workflow/rules/decontaminate.smk

Final updates before v4.0.0 release

---

.readthedocs.yaml
docs/conf.py
docs/requirements.txt
docs/usage.rst

Rework configuration to not use deprecated mechanisms

---

.github/PULL_REQUEST_TEMPLATE.md
sunbeamlib/post.py
workflow/Snakefile
workflow/scripts/remove_low_complexity.py

Remove annoyances

---

src/sunbeamlib/qc.py

Fix remove_low_complexity logic

---

environment.yml

Fix snakemake to 7.32

---

install.sh
src/sunbeamlib/script_run.py
tests/config_fixture.py
tests/e2e/test_sunbeam_extend.py
tests/e2e/test_sunbeam_run.py
workflow/Snakefile

Include and exclude options for sunbeam run

---

.github/workflows/test_slurm.yml
environment.yml
install.sh
pyproject.toml
src/sunbeamlib/slurm_profile.yaml
workflow/Snakefile

Upgrade snakemake to v8

---

docs/install.rst
install.sh

Fix install.sh

---

.github/workflows/dockerhub.yml
.github/workflows/push.yml
.gitignore
Dockerfile
README.md
docs/conf.py
docs/examples.rst
docs/index.rst
docs/quickstart.rst
docs/requirements.txt
docs/usage.rst
environment.yml
install.sh
pyproject.toml
slim.Dockerfile
src/sunbeamlib/__init__.py
src/sunbeamlib/apptainer_profile.yaml
workflow/Snakefile
workflow/envs/cutadapt.Dockerfile
workflow/envs/komplexity.Dockerfile
workflow/envs/qc.Dockerfile
workflow/envs/reports.Dockerfile
workflow/rules/decontaminate.smk
workflow/rules/qc.smk

455 restructure containerization

---

dev_scripts/generate_and_push_docker_image.sh
src/sunbeamlib/__init__.py
workflow/envs/qc.Dockerfile

460 fix docker tagging

---

.github/workflows/dockerhub.yml
Dockerfile
slim.Dockerfile

Pass SUNBEAM_VER from workflow to Dockerfiles

---

.github/workflows/release.yml
install.sh

4.5.2 release

---

.github/workflows/dockerhub.yml
.github/workflows/release.yml
install.sh

4.5.2.dev2 release

---

.github/workflows/dockerhub.yml
.github/workflows/release.yml
install.sh

4.5.2.dev3 release

---

.github/workflows/dockerhub.yml
.github/workflows/release.yml
install.sh

4.5.2.dev4 release

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/dockerhub.yml
.github/workflows/release.yml
Dockerfile
install.sh
slim.Dockerfile
workflow/envs/cutadapt.Dockerfile
workflow/envs/komplexity.Dockerfile
workflow/envs/qc.Dockerfile
workflow/envs/reports.Dockerfile

4.5.2.dev5 release

---

.github/workflows/release.yml
install.sh

4.5.2.dev7 Release

---

workflow/rules/qc.smk

Check for adapter template
